apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: pv-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-env
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-server-data-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-server-data-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-labels
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-server-data-labels
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tensorboard-logs
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-tensorboard-logs
