version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    container_name: s3
    ports:
      - "9000:9000"
    command: minio server data/

  aws:
    image: amazon/aws-cli
    container_name: aws-cli
    command: -c "sleep 2 && aws --endpoint-url http://minio:9000 s3 mb s3://dvc-art --region eu-west-1 || exit 0"
    entrypoint: [/bin/bash]
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - minio
